export const MARK_JABAY_STORE = {
    "authentication":{
       "accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.IlwicE52ZlhXVHBEcEtPQUVVdDdPQkozNjhZTTAtNGQ1aWhyVTZhNlNVM3ZHbWRzV3pkSGoxTWNFN2JnUi1ZeTIzQlwiIg.b0YkXzHhf5g36aVPHDtB6LZAyp4NVxSkKXd3QtxTZAU",
       "clientSecret":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.IlwiSk5UTzM3M0hpTS1UekdHUnFPaEEtNWwtdDVwWGthY25GMXVBS2h0aGhZYjF4dnpHWnNtZ3h4N2pKRU12VUZXUzlEOGxuVHc5SENtY3hVU21IU3BfRmRhUlV6OUN0MzRZUlpfU1ZCZEg1Q2o5MmR5S3hYcHZKUEpSN1V5cjk1S3J6cG0wVkpxYWhZZWdPM3RZa3hCdTlnUkJwZzE5RWR0cmFOR29DQmxyZTR4ZzN6TUFCODRZYnp3QVFYM1gycktXNlczYjgyU1lzVlRRUkQxNkctUzA3alpnWmlpOVBvY0FxWlJfMlVVUUNUWVBlbTl4eG14TXRQdGI3WUFNZ2RCXCIi.hkTlxscHXftV5Z1N5XF7SCsxtP4VQFoLEGuHU7aba2Y",
       "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.IlwiREVvRERxZ3JLc1lWRU5fczI0Z3ozb0JGU29LOWhqSGZocUVSTnl3OXNxUXk2NVNSWEdKLTQzVlZ3X3lCTkxlVkFuUmRGdXZIS3Z2M1Vkb0tJNHBFOE54T2hRR244bEZuY1lNU0llZkUxTHZmWVpibW1xTXI1NmhRZVJEY2RrUXc4TlNiam9zZUpMazNxTF80ODFROG4wWDVWX1FRWTJxUzNoZ3BtLUxIbEtMUmhLOE1idGQ1LTc1cGhZSDBTdWxBRGVXSlVDd1hpZ3lsMnBOS2Z5NFpCYTVXcEhndlNnNWR1Wk0zOFVNZFB3X2dOS2FDZ2NzeWRZQllWSGxfMFBrXCIi.eRskkEI-ZGvTT20JUyv9ApMhWsu1c6sOamETzqAMTyE"
    },
    "userInformation":{
       "profile":{
          "firstName":"Mark Augustine",
          "middleName":"Maglantay",
          "lastName":"Jabay",
          "nickName":"Jabs",
          "email":"",
          "username":"mark.jabay",
          "picture":"g2xXGIIyRwpYYwlaygEUJVC6FPgZfe26LfXAgC0bmsr6B3rySHOheENkVh7H95Rm.jpeg",
          "pictureThumbnail":"AO6pJ7ePJDwEr2p9DiMFObLYnX8tMt5WnIQiUCXqaKFfspYli3W01phwhvda3E8j.jpeg",
          "picturePublicUrl":"https://storage.googleapis.com/hrispublicbucket/<EMPLOYEE_CODE>/<BUCKET_CODE>/PROFILE/<FILENAME> ",
          "bucketCode":"OmY6tlV4SM2pEDEsMjzspw==",
          "employeeCode":"-jFnY2eE0ckPOX8DtymHhQ==",
          "accountType":"EMAPTA_INTERNAL",
          "position":"Mid Quality Assurance Associate",
          "decryptedEmployeeCode":"19-0890",
          "decryptedBucketCode":"BCKT-00001"
       },
       "company":{
          "siteCode":"OSB",
          "siteAddress":"2/F Orient Square Building (OSB), F. Ortigas Avenue (Emerald Avenue), Ortigas Business Center, Pasig City 1605",
          "divisionCode":[
             {
                "company_department_division_code":"kN181I2PfGmjX-F1"
             }
          ],
          "departmentCode":"a1BdTGRNsflIqWs6",
          "companyCode":"jkRC7LoTCSFUKnormns32g==",
          "decryptedCompanyCode":"CMP-000001",
          "teams":[
             {
                "employee_team_code":"2sof0q1bc51IywFr"
             }
          ],
          "departments":[
             {
                "employee_department_code":"BTUwy29nk5qJnxZs"
             },
             {
                "employee_department_code":"_rFcLXhJDFYNXwi2"
             },
             {
                "employee_department_code":"_xOglXcPucAHsAVk"
             },
             {
                "employee_department_code":"5ZqdqwzJarQnsNdn"
             },
             {
                "employee_department_code":"a1BdTGRNsflIqWs6"
             }
          ],
          "departmentName":"Enterprise Change Management, Business Strategy and Support",
          "companies":[
             "CMP-000001"
          ],
          "companyName":"EMAPTA",
          "companyLogo":"https://assets.empowerteams.io/images/logo-emapta192px.jpg",
          "companyThumbnail":"https://assets.empowerteams.io/images/logo-emapta192px.jpg",
          "companyHeader":"https://assets.empowerteams.io/images/img-emapta-banner4.jpg",
          "teamName":"Quality Assurance",
          "teamCode":"2sof0q1bc51IywFr",
          "companyConfigAllowBypass": true,
          "companyConfigBypassPillars": ["OTR", "CSR", "LVR", "TAR", "TOR"]
       },
       "config":{
          "isAllowRemoteAccess":true,
          "companyOtToilFillingPeriod":"PER_CUTOFF",
          "companyOtToilFillingPeriodDays":"0",
          "companyOtToilStart":"2021-07-08",
          "companyOtToilEnd":"2021-07-14",
          "companyConfigSupportedPillar":[
             "OTR",
             "LEAVE",
             "DTR",
             "CSR"
          ],
          "employeeConfigHolidayToFollow":[
             "PH"
          ],
          "employeeConfigHolidayAdditional":[
             "tpvf-UgBRsyowD1W"
          ],
          "ipPermission":false,
          "submitCountdown": 3
       },
       "roles":{
          
       },
       "view":"TALENT",
       "version1UserInfo":{
          "username":"mark.jabay",
          "first_name":"Mark Augustine",
          "last_name":"Jabay",
          "middle_name":"Maglantay",
          "email":"",
          "account_type":"EMAPTA_INTERNAL",
          "user_type":"TALENT",
          "employee_code":"19-0890",
          "company_code":"CMP-000001",
          "companies":[
             "CMP-000001"
          ],
          "bucket_code":"BCKT-00001",
          "encrypted_employee_code":"-jFnY2eE0ckPOX8DtymHhQ==",
          "profile_pic":"g2xXGIIyRwpYYwlaygEUJVC6FPgZfe26LfXAgC0bmsr6B3rySHOheENkVh7H95Rm.jpeg",
          "profile_pic_thumb":"AO6pJ7ePJDwEr2p9DiMFObLYnX8tMt5WnIQiUCXqaKFfspYli3W01phwhvda3E8j.jpeg",
          "is_allow_remote_access":true,
          "department":"a1BdTGRNsflIqWs6",
          "employee_teams":[
             {
                "employee_team_code":"2sof0q1bc51IywFr"
             }
          ],
          "department_name":"Enterprise Change Management, Business Strategy and Support",
          "employee_nick_name":"Jabs",
          "encrypted_bucket_code":"OmY6tlV4SM2pEDEsMjzspw==",
          "team_code":"2sof0q1bc51IywFr",
          "team_name":"Quality Assurance",
          "departments":[
             {
                "employee_department_code":"BTUwy29nk5qJnxZs"
             },
             {
                "employee_department_code":"_rFcLXhJDFYNXwi2"
             },
             {
                "employee_department_code":"_xOglXcPucAHsAVk"
             },
             {
                "employee_department_code":"5ZqdqwzJarQnsNdn"
             },
             {
                "employee_department_code":"a1BdTGRNsflIqWs6"
             }
          ],
          "site_code":"OSB",
          "division":[
             {
                "company_department_division_code":"kN181I2PfGmjX-F1"
             }
          ],
          "position":"Mid Quality Assurance Associate",
          "ip_address":"192.168.254.132",
          "company_name":"EMAPTA",
          "company_logo":"https://assets.empowerteams.io/images/logo-emapta192px.jpg",
          "company_thumbnail":"https://assets.empowerteams.io/images/logo-emapta192px.jpg",
          "company_ot_toil_filling_period":"PER_CUTOFF",
          "company_ot_toil_filling_period_days":"0",
          "company_ot_toil_start":"2021-07-08",
          "company_ot_toil_end":"2021-07-14",
          "company_config_supported_pillar":[
             "OTR",
             "LEAVE",
             "DTR",
             "CSR"
          ],
          "company_header":"https://assets.empowerteams.io/images/img-emapta-banner4.jpg",
          "employee_config_holiday_to_follow":[
             "PH"
          ],
          "employee_config_holiday_additional":[
             "tpvf-UgBRsyowD1W"
          ]
       }
    },
    "user":{
       "user":{
          "_tkn":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.IntcImJ1Y2tldF9jb2RlXCI6XCJPbVk2dGxWNFNNMnBFREVzTWp6c3B3PT1cIixcImVtcGxveWVlX2NvZGVcIjpcIi1qRm5ZMmVFMGNrUE9YOER0eW1IaFE9PVwiLFwiaXNfYWxsb3dfcmVtb3RlX2FjY2Vzc1wiOnRydWUsXCJzaXRlX2NvZGVcIjpcIk9TQlwiLFwic2l0ZV9hZGRyZXNzXCI6XCIyL0YgT3JpZW50IFNxdWFyZSBCdWlsZGluZyAoT1NCKSwgRi4gT3J0aWdhcyBBdmVudWUgKEVtZXJhbGQgQXZlbnVlKSwgT3J0aWdhcyBCdXNpbmVzcyBDZW50ZXIsIFBhc2lnIENpdHkgMTYwNVwiLFwidXNlcm5hbWVcIjpcIm1hcmsuamFiYXlcIixcImRpdmlzaW9uX2NvZGVcIjpbe1wiY29tcGFueV9kZXBhcnRtZW50X2RpdmlzaW9uX2NvZGVcIjpcImtOMTgxSTJQZkdtalgtRjFcIn1dLFwiZW1wbG95ZWVfZmlyc3RfbmFtZVwiOlwiTWFyayBBdWd1c3RpbmVcIixcImRlcGFydG1lbnRfY29kZVwiOlwiYTFCZFRHUk5zZmxJcVdzNlwiLFwidGVhbV9jb2RlXCI6XCIyc29mMHExYmM1MUl5d0ZyXCIsXCJlbXBsb3llZV9sYXN0X25hbWVcIjpcIkphYmF5XCIsXCJlbXBsb3llZV9taWRkbGVfbmFtZVwiOlwiTWFnbGFudGF5XCIsXCJlbXBsb3llZV9uaWNrX25hbWVcIjpcIkphYnNcIixcInByb2ZpbGVfcGljXCI6XCJnMnhYR0lJeVJ3cFlZd2xheWdFVUpWQzZGUGdaZmUyNkxmWEFnQzBibXNyNkIzcnlTSE9oZUVOa1ZoN0g5NVJtLmpwZWdcIixcInByb2ZpbGVfcGljX3RodW1iXCI6XCJBTzZwSjdlUEpEd0VyMnA5RGlNRk9iTFluWDh0TXQ1V25JUWlVQ1hxYUtGZnNwWWxpM1cwMXBod2h2ZGEzRThqLmpwZWdcIixcInByb2ZpbGVfcHVibGljX3VybFwiOlwiaHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL2hyaXNwdWJsaWNidWNrZXQvPEVNUExPWUVFX0NPREU-LzxCVUNLRVRfQ09ERT4vUFJPRklMRS88RklMRU5BTUU-IFwiLFwiZW1wbG95ZWVfZW1haWxcIjpcIlwiLFwiZW1wbG95ZWVfYWNjb3VudF90eXBlXCI6XCJFTUFQVEFfSU5URVJOQUxcIixcImNvbXBhbnlfY29kZVwiOlwiamtSQzdMb1RDU0ZVS25vcm1uczMyZz09XCIsXCJhY2Nlc3NfdG9rZW5cIjpcInBOdmZYV1RwRHBLT0FFVXQ3T0JKMzY4WU0wLTRkNWloclU2YTZTVTN2R21kc1d6ZEhqMU1jRTdiZ1ItWXkyM0JcIixcInRlYW1zXCI6W3tcImVtcGxveWVlX3RlYW1fY29kZVwiOlwiMnNvZjBxMWJjNTFJeXdGclwifV0sXCJkZXBhcnRtZW50c1wiOlt7XCJlbXBsb3llZV9kZXBhcnRtZW50X2NvZGVcIjpcIkJUVXd5MjluazVxSm54WnNcIn0se1wiZW1wbG95ZWVfZGVwYXJ0bWVudF9jb2RlXCI6XCJfckZjTFhoSkRGWU5Yd2kyXCJ9LHtcImVtcGxveWVlX2RlcGFydG1lbnRfY29kZVwiOlwiX3hPZ2xYY1B1Y0FIc0FWa1wifSx7XCJlbXBsb3llZV9kZXBhcnRtZW50X2NvZGVcIjpcIjVacWRxd3pKYXJRbnNOZG5cIn0se1wiZW1wbG95ZWVfZGVwYXJ0bWVudF9jb2RlXCI6XCJhMUJkVEdSTnNmbElxV3M2XCJ9XSxcImRlcGFydG1lbnRfbmFtZVwiOlwiRW50ZXJwcmlzZSBDaGFuZ2UgTWFuYWdlbWVudCwgQnVzaW5lc3MgU3RyYXRlZ3kgYW5kIFN1cHBvcnRcIixcInRlYW1fbmFtZVwiOlwiUXVhbGl0eSBBc3N1cmFuY2VcIixcImFjY2Vzc190b2tlbl9lbmNyeXB0XCI6XCJlNzcwNTllZDBjMjJiZDZjYWM1MDgyMWRiMzU0Mjg1OGNhNGU1YjgyOWE5ZmJkYTQ5YjA2MThlNGQwYTYwOGZlcE52ZlhXVHBEcEtPQUVVdDdPQkozNjhZTTAtNGQ1aWhyVTZhNlNVM3ZHbWRzV3pkSGoxTWNFN2JnUi1ZeTIzQlwiLFwiYWNjZXNzX3Rva2VuX2RlY3J5cHRfY29kZVwiOlwiYXloXzg4b1c4NkJfV1g2WFRhLW1wVl96R0lCYnB6Mk9cIixcImV4cGlyZXNcIjozMDAsXCJyZWZyZXNoX3Rva2VuXCI6XCJERW9ERHFncktzWVZFTl9zMjRnejNvQkZTb0s5aGpIZmhxRVJOeXc5c3FReTY1U1JYR0otNDNWVndfeUJOTGVWQW5SZEZ1dkhLdnYzVWRvS0k0cEU4TnhPaFFHbjhsRm5jWU1TSWVmRTFMdmZZWmJtbXFNcjU2aFFlUkRjZGtRdzhOU2Jqb3NlSkxrM3FMXzQ4MVE4bjBYNVZfUVFZMnFTM2hncG0tTEhsS0xSaEs4TWJ0ZDUtNzVwaFlIMFN1bEFEZVdKVUN3WGlneWwycE5LZnk0WkJhNVdwSGd2U2c1ZHVaTTM4VU1kUHdfZ05LYUNnY3N5ZFlCWVZIbF8wUGtcIixcImNsaWVudF9zZWNyZXRcIjpcIkpOVE8zNzNIaU0tVHpHR1JxT2hBLTVsLXQ1cFhrYWNuRjF1QUtodGhoWWIxeHZ6R1pzbWd4eDdqSkVNdlVGV1M5RDhsblR3OUhDbWN4VVNtSFNwX0ZkYVJVejlDdDM0WVJaX1NWQmRINUNqOTJkeUt4WHB2SlBKUjdVeXI5NUtyenBtMFZKcWFoWWVnTzN0WWt4QnU5Z1JCcGcxOUVkdHJhTkdvQ0JscmU0eGczek1BQjg0WWJ6d0FRWDNYMnJLVzZXM2I4MlNZc1ZUUVJEMTZHLVMwN2paZ1ppaTlQb2NBcVpSXzJVVVFDVFlQZW05eHhteE10UHRiN1lBTWdkQlwiLFwiY29tcGFuaWVzXCI6W1wiQ01QLTAwMDAwMVwiXSxcInBvc2l0aW9uXCI6XCJNaWQgUXVhbGl0eSBBc3N1cmFuY2UgQXNzb2NpYXRlXCIsXCJjb21wYW55X25hbWVcIjpcIkVNQVBUQVwiLFwiY29tcGFueV9sb2dvXCI6XCJodHRwczovL2Fzc2V0cy5lbXBvd2VydGVhbXMuaW8vaW1hZ2VzL2xvZ28tZW1hcHRhMTkycHguanBnXCIsXCJjb21wYW55X3RodW1ibmFpbFwiOlwiaHR0cHM6Ly9hc3NldHMuZW1wb3dlcnRlYW1zLmlvL2ltYWdlcy9sb2dvLWVtYXB0YTE5MnB4LmpwZ1wiLFwiY29tcGFueV9oZWFkZXJcIjpcImh0dHBzOi8vYXNzZXRzLmVtcG93ZXJ0ZWFtcy5pby9pbWFnZXMvaW1nLWVtYXB0YS1iYW5uZXI0LmpwZ1wiLFwiY29tcGFueV9vdF90b2lsX2ZpbGxpbmdfcGVyaW9kXCI6XCJQRVJfQ1VUT0ZGXCIsXCJjb21wYW55X2NvbmZpZ19hbGxvd19ieXBhc3NcIjpmYWxzZSxcImNvbXBhbnlfY29uZmlnX2J5cGFzc19waWxsYXJcIjpudWxsLFwiY29tcGFueV9vdF90b2lsX2ZpbGxpbmdfcGVyaW9kX2RheXNcIjpcIjBcIixcImNvbXBhbnlfb3RfdG9pbF9zdGFydFwiOlwiMjAyMS0wNy0wOFwiLFwiY29tcGFueV9vdF90b2lsX2VuZFwiOlwiMjAyMS0wNy0xNFwiLFwiY29tcGFueV9jb25maWdfc3VwcG9ydGVkX3BpbGxhclwiOltcIk9UUlwiLFwiTEVBVkVcIixcIkRUUlwiLFwiQ1NSXCJdLFwiZW1wbG95ZWVfY29uZmlnX2hvbGlkYXlfdG9fZm9sbG93XCI6W1wiUEhcIl0sXCJlbXBsb3llZV9jb25maWdfaG9saWRheV9hZGRpdGlvbmFsXCI6W1widHB2Zi1VZ0JSc3lvd0QxV1wiXSxcImNvbXBhbnlfY29uZmlnX3ByZXZpZXdfY291bnRkb3duXCI6XCJcIixcInVzZXJfdHlwZVwiOlwiVEFMRU5UXCJ9Ig.pIptsvKWNSXWNy5grrF2hiKzh_mFrvHqD7aVu1dywyo",
          "systems":{
             "TALENT":{
                "menus":{
                   "sidebar":{
                      "pages":{
                         "home":{
                            "label":"Home",
                            "link":"/",
                            "class":"link-home",
                            "platform":"PAGE"
                         },
                         "my_attendance":{
                            "label":"My Attendance",
                            "link":"/attendance",
                            "class":"link-attendance"
                         },
                         "requests":{
                            "label":"Requests",
                            "link":"/requests",
                            "class":"link-requests"
                         },
                         "view_shift":{
                            "label":"View Shift",
                            "link":"/view-shift-schedule",
                            "class":"link-viewshift"
                         },
                         "news_feed":{
                            "label":"News Feed",
                            "link":"/news-feed",
                            "class":"link-newsfeed"
                         },
                         "channels":{
                            "label":"Channels",
                            "link":"",
                            "class":"link-channels",
                            "is_child_collapse":false,
                            "children":{
                               "payroll_services":{
                                  "label":"Payroll Services",
                                  "link":"/channel/ALL/1",
                                  "class":"item-payroll",
                                  "platform":"PAGE"
                               },
                               "shop_and_rewards_orders":{
                                  "label":"Shop & Rewards Orders",
                                  "link":"/channel/shop-and-rewards/ALL/1",
                                  "class":"item-shoprewards",
                                  "platform":"PAGE"
                               }
                            }
                         },
                         "shop_and_rewards":{
                            "label":"Shop & Rewards",
                            "link":"/shop-and-rewards",
                            "class":"link-shoprewards",
                            "platform":"PAGE"
                         },
                         "leave_balance":{
                            "label":"Leave Balance",
                            "link":"/leave-balance",
                            "class":"leave-balance"
                         }
                      },
                      "support_team_list":true
                   },
                   "top_menu":{
                      "announcements":true,
                      "notifications":true,
                      "impersonate":true,
                      "faqs":true,
                      "logo":true,
                      "collapsible":true,
                      "time_recorder":true,
                      "profile":[
                         "ACCOUNT_PROFILE",
                         "LOGOUT",
                         "THEMES",
                         "OPEN_TICKET"
                      ]
                   },
                   "express_actions":{
                      "role_based":{
                         "payroll_services":{
                            "label":"Payroll Services",
                            "link":"/channel/ALL/1",
                            "class":"item-payroll",
                            "platform":"PAGE"
                         },
                         "shop_and_rewards_exp":{
                            "label":"Shop & Rewards",
                            "link":"/shop-and-rewards",
                            "class":"link-shoprewards",
                            "platform":"PAGE",
                            "is_default":true
                         },
                         "LEAVE":{
                            "label":"File a Leave",
                            "link":"/file-lvr",
                            "class":"item-leave",
                            "platform":"PAGE",
                            "is_default":true
                         },
                         "AMENDMENT":{
                            "label":"DTR Amendment",
                            "link":"/file-tar",
                            "class":"item-amend",
                            "platform":"PAGE"
                         },
                         "CHANGE_SHIFT":{
                            "label":"Change Schedule",
                            "link":"/view-shift-schedule",
                            "class":"item-changeshift",
                            "platform":"PAGE"
                         },
                         "OVERTIME":{
                            "label":"File Overtime",
                            "link":"/file-otr",
                            "class":"item-overtime",
                            "platform":"PAGE",
                            "is_default":true
                         },
                         "EMERGENCY_NUMBERS":{
                            "label":"Emergency Numbers",
                            "link":"",
                            "class":"item-emergencynumbers",
                            "platform":"MODAL"
                         }
                      }
                   }
                },
                "composition_code":"COMP-20-000000000032",
                "composition_code_extra":"COMP-20-000000000032_OTR"
             },
             "CLIENT":{
                "menus":{
                   "sidebar":{
                      "pages":{
                         "home":{
                            "label":"Home",
                            "link":"/",
                            "class":"link-home",
                            "platform":"PAGE"
                         },
                         "time_and_attendance":{
                            "label":"Time & Attendance",
                            "link":"/attendance",
                            "class":"link-attendance"
                         },
                         "requests":{
                            "label":"Requests",
                            "link":"/requests",
                            "class":"link-requests"
                         },
                         "talent_directory":{
                            "label":"Talent Directory",
                            "link":"/talents",
                            "class":"link-talentdirectory"
                         },
                         "news_feed":{
                            "label":"News Feed",
                            "link":"/news-feed",
                            "class":"link-newsfeed"
                         },
                         "team_leave_balance":{
                            "label":"Team Leave Balance",
                            "link":"/leave-balance",
                            "class":"link-teamleavebalance"
                         },
                         "dtr_leave_extract":{
                            "label":"Time Record Extractor",
                            "link":"/time-record-extractor",
                            "class":"link-clientextract",
                            "platform":"PAGE"
                         },
                         "view_employee_shift":{
                            "label":"View Employee Shift",
                            "link":"/view-employee-shift",
                            "class":"link-viewshift",
                            "platform":"PAGE"
                         }
                      },
                      "support_team_list":true
                   },
                   "top_menu":{
                      "faqs":true,
                      "logo":true,
                      "collapsible":true,
                      "impersonate":true,
                      "announcements":true,
                      "notifications":true,
                      "time_recorder":true,
                      "profile":[
                         "ACCOUNT_PROFILE",
                         "LOGOUT",
                         "THEMES",
                         "OPEN_TICKET"
                      ]
                   },
                   "express_actions":{
                      "main":{
                         "dtr_leave_extract":{
                            "label":"Time Record Extractor",
                            "link":"/time-record-extractor",
                            "class":"link-clientextract",
                            "platform":"PAGE",
                            "is_default":true
                         },
                         "EMERGENCY_NUMBERS":{
                            "label":"Emergency Numbers",
                            "link":"",
                            "class":"item-emergencynumbers",
                            "platform":"MODAL"
                         },
                         "ANNOUNCEMENT":{
                            "label":"Make an Announcement",
                            "link":"/create-announcement",
                            "class":"item-makeannouncement",
                            "platform":"PAGE"
                         }
                      },
                      "role_based":{
                         "PREAPPROVE_OVERTIME":{
                            "label":"Pre-Approved Overtime",
                            "link":"/file-pre-approve-otr",
                            "class":"item-preapproveovertime",
                            "platform":"PAGE",
                            "is_default":true
                         },
                         "PROCESS_REQUEST":{
                            "label":"Process Request",
                            "link":"/requests",
                            "class":"item-processrequest",
                            "platform":"PAGE",
                            "is_default":true
                         },
                         "PREAPPROVE_CHANGE_SHIFT":{
                            "label":"File Shift Schedule",
                            "link":"/view-employee-shift",
                            "class":"item-preapprovechangeshift",
                            "platform":"PAGE"
                         }
                      }
                   }
                },
                "composition_code":"COMP-19-000000000002",
                "composition_code_extra":"COMP-19-000000000002"
             },
             "HR":{
                "menus":{
                   "top_menu":{
                      "faqs":true,
                      "logo":true,
                      "collapsible":true,
                      "impersonate":true,
                      "notifications":true,
                      "time_recorder":true,
                      "profile":[
                         "ACCOUNT_PROFILE",
                         "LOGOUT",
                         "THEMES",
                         "OPEN_TICKET"
                      ]
                   },
                   "express_actions":{
                      "main":{
                         "EMERGENCY_NUMBERS":{
                            "label":"Emergency Numbers",
                            "link":"",
                            "class":"item-emergencynumbers",
                            "platform":"MODAL"
                         }
                      },
                      "role_based":{
                         "PREAPPROVE_OVERTIME":{
                            "label":"Pre-Approved Overtime",
                            "link":"/file-pre-approve-otr",
                            "class":"item-preapproveovertime",
                            "platform":"PAGE",
                            "is_default":true
                         },
                         "PREAPPROVE_TOIL":{
                            "label":"Pre-Approved TOIL",
                            "link":"/file-pre-approve-toil",
                            "class":"item-preapprovetoil",
                            "platform":"PAGE",
                            "is_default":true
                         },
                         "team_leave_balance":{
                            "label":"Team Leave Balance",
                            "link":"/leave-balance",
                            "class":"link-teamleavebalance"
                         },
                         "admin_employee_data_extract":{
                            "label":"Employee Info Report",
                            "link":"/personal-data-extract",
                            "class":"link-employeeinforeport"
                         },
                         "dtr_monitoring_data_extract":{
                            "label":"DTR Report Extraction",
                            "link":"/dtr-data-monitoring-extract",
                            "class":"link-dtrreportextraction"
                         },
                         "PROCESS_REQUEST":{
                            "label":"Process Request",
                            "link":"/requests",
                            "class":"item-processrequest",
                            "platform":"PAGE",
                            "is_default":true
                         },
                         "PREAPPROVE_CHANGE_SHIFT":{
                            "label":"File Shift Schedule",
                            "link":"/file-csr",
                            "class":"item-preapprovechangeshift",
                            "platform":"PAGE"
                         }
                      }
                   },
                   "sidebar":{
                      "pages":{
                         "home":{
                            "label":"Home",
                            "link":"/",
                            "class":"link-home",
                            "platform":"PAGE"
                         },
                         "time_and_attendance":{
                            "label":"Time & Attendance",
                            "link":"/attendance",
                            "class":"link-attendance"
                         },
                         "talent_directory":{
                            "label":"Talent Directory",
                            "link":"/talents-conso",
                            "class":"link-talentdirectory"
                         },
                         "department_directory":{
                            "label":"Department Directory",
                            "link":"/departments",
                            "class":"link-clientdirectory"
                         },
                         "client_directory":{
                            "label":"Client Directory",
                            "link":"/clients-conso",
                            "class":"link-clientsconso"
                         },
                         "requests":{
                            "label":"Requests",
                            "link":"/requests",
                            "class":"link-requests"
                         },
                         "news_feed":{
                            "label":"News Feed",
                            "link":"/news-feed",
                            "class":"link-newsfeed"
                         },
                         "team_leave_balance":{
                            "label":"Team Leave Balance",
                            "link":"/leave-balance",
                            "class":"link-teamleavebalance"
                         },
                         "admin_employee_data_extract":{
                            "label":"Employee Info Report",
                            "link":"/personal-data-extract",
                            "class":"link-employeeinforeport"
                         },
                         "dtr_monitoring_data_extract":{
                            "label":"DTR Report Extraction",
                            "link":"/dtr-data-monitoring-extract",
                            "class":"link-dtrreportextraction"
                         },
                         "view_employee_shift":{
                            "label":"View Employee Shift",
                            "link":"/view-employee-shift",
                            "class":"link-viewshift",
                            "platform":"PAGE"
                         }
                      },
                      "support_team_list":true
                   }
                },
                "composition_code":"COMP-20-000000000012",
                "composition_code_extra":"COMP-20-000000000012"
             },
             "RECRUITER":{
                "menus":{
                   "sidebar":{
                      "pages":{
                         "home":{
                            "label":"Home",
                            "link":"/",
                            "class":"link-home",
                            "platform":"PAGE"
                         },
                         "news_feed":{
                            "label":"News Feed",
                            "link":"/news-feed",
                            "class":"link-newsfeed"
                         },
                         "fsp":{
                            "label":"Final Staffing Proposal",
                            "link":"/final-staffing-proposal",
                            "class":"link-finalstaffingproposal"
                         },
                         "nha_extractor":{
                            "label":"NHA Extractor",
                            "link":"/nha-extractor",
                            "class":"link-nhaextractor"
                         }
                      },
                      "support_team_list":true
                   },
                   "top_menu":{
                      "logo":true,
                      "faqs":true,
                      "announcements":true,
                      "notifications":true,
                      "collapsible":true,
                      "impersonate":true,
                      "time_recorder":true,
                      "special_privilege":{
                         "is_allow_download":true,
                         "is_allow_etap":true
                      },
                      "profile":[
                         "ACCOUNT_PROFILE",
                         "LOGOUT",
                         "THEMES",
                         "OPEN_TICKET"
                      ]
                   },
                   "express_actions":{
                      "main":[
                         
                      ],
                      "role_based":{
                         "fsp_exa":{
                            "label":"Final Staffing Proposal",
                            "link":"/final-staffing-proposal",
                            "class":"link-finalstaffingproposal"
                         },
                         "nha_extractor_exa":{
                            "label":"NHA Extractor",
                            "link":"/nha-extractor",
                            "class":"link-nhaextractor"
                         }
                      }
                   }
                },
                "composition_code":"COMP-20-000000000017",
                "composition_code_extra":"COMP-20-000000000017"
             },
             "ADMIN":{
                "menus":{
                   "top_menu":{
                      "faqs":true,
                      "logo":true,
                      "collapsible":true,
                      "impersonate":true,
                      "notifications":false,
                      "time_recorder":false,
                      "announcements":false,
                      "profile":[
                         "ACCOUNT_PROFILE",
                         "LOGOUT",
                         "THEMES",
                         "OPEN_TICKET"
                      ]
                   },
                   "sidebar":{
                      "support_team_list":false,
                      "pages":{
                         "admin_job_lists":{
                            "label":"Job Title",
                            "link":"/admin-job-lists",
                            "class":"link-jobtitle"
                         },
                         "admin_site_list":{
                            "label":"Site",
                            "link":"/admin-site-list",
                            "class":"link-site"
                         },
                         "admin_division_list":{
                            "label":"Division",
                            "link":"/admin-division-list",
                            "class":"link-division"
                         },
                         "admin_department_list":{
                            "label":"Department",
                            "link":"/admin-department-list",
                            "class":"link-department"
                         },
                         "admin_team_list":{
                            "label":"Team",
                            "link":"/admin-team-list",
                            "class":"link-team"
                         },
                         "admin_holiday_management":{
                            "label":"Holiday Management",
                            "link":"",
                            "class":"link-holidaymanagement",
                            "is_child_collapse":false,
                            "children":{
                               "admin_holiday_list":{
                                  "label":"Holiday List",
                                  "link":"/admin-holiday-list",
                                  "class":""
                               },
                               "admin_assign_holiday":{
                                  "label":"Assign Holidays",
                                  "link":"/admin-assign-holidays",
                                  "class":""
                               }
                            }
                         },
                         "admin_audit_trails":{
                            "label":"Audit Trails",
                            "link":"/admin-audit-trails",
                            "class":"link-audittrails"
                         }
                      }
                   }
                },
                "composition_code":"COMP-20-000000000016",
                "composition_code_extra":"COMP-20-000000000016"
             },
             "PAYROLL":{
                "menus":{
                   "top_menu":{
                      "collapsible":true,
                      "impersonate":true,
                      "announcements":true,
                      "notifications":true,
                      "time_recorder":true,
                      "profile":[
                         "ACCOUNT_PROFILE",
                         "LOGOUT",
                         "THEMES",
                         "OPEN_TICKET"
                      ],
                      "faqs":true,
                      "logo":true
                   },
                   "express_actions":{
                      "main":{
                         "time_and_attendance":{
                            "label":"Time & Attendance",
                            "link":"/attendance",
                            "class":"link-attendance",
                            "is_default":true
                         },
                         "requests":{
                            "label":"Requests",
                            "link":"/requests",
                            "class":"link-requests",
                            "is_default":true
                         },
                         "team_leave_balance":{
                            "label":"Team Leave Balance",
                            "link":"/leave-balance",
                            "class":"link-teamleavebalance"
                         },
                         "payroll_extract":{
                            "label":"Payroll Extract",
                            "link":"/admin-payroll-extract",
                            "class":"link-payrollextract"
                         },
                         "employee_data_extract":{
                            "label":"Employee Info Report",
                            "link":"/personal-data-extract",
                            "class":"link-employeeinforeport"
                         }
                      },
                      "role_based":{
                         "payroll_services":{
                            "label":"Payroll Services",
                            "link":"/channel/ALL/1",
                            "class":"item-payroll",
                            "platform":"PAGE",
                            "is_default":true
                         }
                      }
                   },
                   "sidebar":{
                      "pages":{
                         "home":{
                            "label":"Home",
                            "link":"/",
                            "class":"link-home",
                            "platform":"PAGE"
                         },
                         "time_and_attendance":{
                            "label":"Time & Attendance",
                            "link":"/attendance",
                            "class":"link-attendance"
                         },
                         "requests":{
                            "label":"Requests",
                            "link":"/requests",
                            "class":"link-requests"
                         },
                         "talent_directory":{
                            "label":"Talent Directory",
                            "link":"/talents",
                            "class":"link-talentdirectory"
                         },
                         "news_feed":{
                            "label":"News Feed",
                            "link":"/news-feed",
                            "class":"link-newsfeed"
                         },
                         "team_leave_balance":{
                            "label":"Team Leave Balance",
                            "link":"/leave-balance",
                            "class":"link-teamleavebalance"
                         },
                         "payroll_query":{
                            "label":"Payroll Query",
                            "link":"/payroll-query-list",
                            "class":"link-payrollquery"
                         },
                         "payroll_extract":{
                            "label":"Payroll Extract",
                            "link":"/admin-payroll-extract",
                            "class":"link-payrollextract"
                         },
                         "leave_manangement":{
                            "label":"Leave Management",
                            "link":"/admin-add-leave-credit",
                            "class":"link-leavemanagement",
                            "is_child_collapse":false,
                            "children":{
                               "add_leave_credit":{
                                  "label":"Add Leave Credit",
                                  "link":"/admin-add-leave-credit",
                                  "class":"link-newsfeed"
                               }
                            }
                         },
                         "channels":{
                            "label":"Channels",
                            "link":"",
                            "class":"link-channels",
                            "is_child_collapse":false,
                            "children":{
                               "payroll_services":{
                                  "label":"Payroll Services",
                                  "link":"/channel/ALL/1",
                                  "class":"item-payroll",
                                  "platform":"PAGE"
                               }
                            }
                         },
                         "view_employee_shift":{
                            "label":"View Employee Shift",
                            "link":"/view-employee-shift",
                            "class":"link-viewshift",
                            "platform":"PAGE"
                         },
                         "employee_data_extract":{
                            "label":"Employee Info Report",
                            "link":"/personal-data-extract",
                            "class":"link-employeeinforeport"
                         }
                      },
                      "support_team_list":true
                   }
                },
                "composition_code":"COMP-20-000000000009",
                "composition_code_extra":"COMP-20-000000000009"
             }
          },
          "info":{
             "username":"mark.jabay",
             "first_name":"Mark Augustine",
             "last_name":"Jabay",
             "middle_name":"Maglantay",
             "email":"",
             "account_type":"EMAPTA_INTERNAL",
             "user_type":"TALENT",
             "employee_code":"19-0890",
             "company_code":"CMP-000001",
             "companies":[
                "CMP-000001"
             ],
             "bucket_code":"BCKT-00001",
             "encrypted_employee_code":"-jFnY2eE0ckPOX8DtymHhQ==",
             "profile_pic":"g2xXGIIyRwpYYwlaygEUJVC6FPgZfe26LfXAgC0bmsr6B3rySHOheENkVh7H95Rm.jpeg",
             "profile_pic_thumb":"AO6pJ7ePJDwEr2p9DiMFObLYnX8tMt5WnIQiUCXqaKFfspYli3W01phwhvda3E8j.jpeg",
             "is_allow_remote_access":true,
             "department":"a1BdTGRNsflIqWs6",
             "employee_teams":[
                {
                   "employee_team_code":"2sof0q1bc51IywFr"
                }
             ],
             "department_name":"Enterprise Change Management, Business Strategy and Support",
             "employee_nick_name":"Jabs",
             "encrypted_bucket_code":"OmY6tlV4SM2pEDEsMjzspw==",
             "team_code":"2sof0q1bc51IywFr",
             "team_name":"Quality Assurance",
             "departments":[
                {
                   "employee_department_code":"BTUwy29nk5qJnxZs"
                },
                {
                   "employee_department_code":"_rFcLXhJDFYNXwi2"
                },
                {
                   "employee_department_code":"_xOglXcPucAHsAVk"
                },
                {
                   "employee_department_code":"5ZqdqwzJarQnsNdn"
                },
                {
                   "employee_department_code":"a1BdTGRNsflIqWs6"
                }
             ],
             "site_code":"OSB",
             "division":[
                {
                   "company_department_division_code":"kN181I2PfGmjX-F1"
                }
             ],
             "position":"Mid Quality Assurance Associate",
             "ip_address":"192.168.254.132",
             "company_name":"EMAPTA",
             "company_logo":"https://assets.empowerteams.io/images/logo-emapta192px.jpg",
             "company_thumbnail":"https://assets.empowerteams.io/images/logo-emapta192px.jpg",
             "company_ot_toil_filling_period":"PER_CUTOFF",
             "company_ot_toil_filling_period_days":"0",
             "company_ot_toil_start":"2021-07-08",
             "company_ot_toil_end":"2021-07-14",
             "company_config_supported_pillar":[
                "OTR",
                "LEAVE",
                "DTR",
                "CSR"
             ],
             "company_header":"https://assets.empowerteams.io/images/img-emapta-banner4.jpg",
             "employee_config_holiday_to_follow":[
                "PH"
             ],
             "employee_config_holiday_additional":[
                "tpvf-UgBRsyowD1W"
             ]
          },
          "roles":[
             {
                "label":"TALENT",
                "value":"TALENT"
             },
             {
                "label":"CLIENT",
                "value":"CLIENT"
             },
             {
                "label":"HR",
                "value":"HR"
             },
             {
                "label":"RECRUITER",
                "value":"RECRUITER"
             },
             {
                "label":"ADMIN",
                "value":"ADMIN"
             },
             {
                "label":"PAYROLL",
                "value":"PAYROLL"
             }
          ]
       },
       "view":"Talent"
    },
    "presence":{
       "state":{
          "pages":"",
          "status":[
             {
                "value":"ON_SCREEN",
                "label":"On Screen"
             },
             {
                "value":"OFF_SCREEN",
                "label":"Off Screen"
             },
             {
                "value":"INACTIVE",
                "label":"In Active"
             }
          ]
       }
    },
    "accessibility":{
       "lastActiveRequest":1626243227943,
       "lastActiveUrl":null
    },
    "acl":{
       "roles":[
          {
             "label":"TALENT",
             "value":"TALENT"
          },
          {
             "label":"CLIENT",
             "value":"CLIENT"
          },
          {
             "label":"HR",
             "value":"HR"
          },
          {
             "label":"RECRUITER",
             "value":"RECRUITER"
          },
          {
             "label":"ADMIN",
             "value":"ADMIN"
          },
          {
             "label":"PAYROLL",
             "value":"PAYROLL"
          }
       ],
       "systems":{
          "TALENT":{
             "menus":{
                "sidebar":{
                   "pages":{
                      "home":{
                         "label":"Home",
                         "link":"/",
                         "class":"link-home",
                         "platform":"PAGE"
                      },
                      "my_attendance":{
                         "label":"My Attendance",
                         "link":"/attendance",
                         "class":"link-attendance"
                      },
                      "requests":{
                         "label":"Requests",
                         "link":"/requests",
                         "class":"link-requests"
                      },
                      "view_shift":{
                         "label":"View Shift",
                         "link":"/view-shift-schedule",
                         "class":"link-viewshift"
                      },
                      "news_feed":{
                         "label":"News Feed",
                         "link":"/news-feed",
                         "class":"link-newsfeed"
                      },
                      "channels":{
                         "label":"Channels",
                         "link":"",
                         "class":"link-channels",
                         "is_child_collapse":false,
                         "children":{
                            "payroll_services":{
                               "label":"Payroll Services",
                               "link":"/channel/ALL/1",
                               "class":"item-payroll",
                               "platform":"PAGE"
                            },
                            "shop_and_rewards_orders":{
                               "label":"Shop & Rewards Orders",
                               "link":"/channel/shop-and-rewards/ALL/1",
                               "class":"item-shoprewards",
                               "platform":"PAGE"
                            }
                         }
                      },
                      "shop_and_rewards":{
                         "label":"Shop & Rewards",
                         "link":"/shop-and-rewards",
                         "class":"link-shoprewards",
                         "platform":"PAGE"
                      },
                      "leave_balance":{
                         "label":"Leave Balance",
                         "link":"/leave-balance",
                         "class":"leave-balance"
                      }
                   },
                   "support_team_list":true
                },
                "top_menu":{
                   "announcements":true,
                   "notifications":true,
                   "impersonate":true,
                   "faqs":true,
                   "logo":true,
                   "collapsible":true,
                   "time_recorder":true,
                   "profile":[
                      "ACCOUNT_PROFILE",
                      "LOGOUT",
                      "THEMES",
                      "OPEN_TICKET"
                   ]
                },
                "express_actions":{
                   "role_based":{
                      "payroll_services":{
                         "label":"Payroll Services",
                         "link":"/channel/ALL/1",
                         "class":"item-payroll",
                         "platform":"PAGE"
                      },
                      "shop_and_rewards_exp":{
                         "label":"Shop & Rewards",
                         "link":"/shop-and-rewards",
                         "class":"link-shoprewards",
                         "platform":"PAGE",
                         "is_default":true
                      },
                      "LEAVE":{
                         "label":"File a Leave",
                         "link":"/file-lvr",
                         "class":"item-leave",
                         "platform":"PAGE",
                         "is_default":true
                      },
                      "AMENDMENT":{
                         "label":"DTR Amendment",
                         "link":"/file-tar",
                         "class":"item-amend",
                         "platform":"PAGE"
                      },
                      "CHANGE_SHIFT":{
                         "label":"Change Schedule",
                         "link":"/view-shift-schedule",
                         "class":"item-changeshift",
                         "platform":"PAGE"
                      },
                      "OVERTIME":{
                         "label":"File Overtime",
                         "link":"/file-otr",
                         "class":"item-overtime",
                         "platform":"PAGE",
                         "is_default":true
                      },
                      "EMERGENCY_NUMBERS":{
                         "label":"Emergency Numbers",
                         "link":"",
                         "class":"item-emergencynumbers",
                         "platform":"MODAL"
                      }
                   }
                }
             },
             "composition_code":"COMP-20-000000000032",
             "composition_code_extra":"COMP-20-000000000032_OTR"
          },
          "CLIENT":{
             "menus":{
                "sidebar":{
                   "pages":{
                      "home":{
                         "label":"Home",
                         "link":"/",
                         "class":"link-home",
                         "platform":"PAGE"
                      },
                      "time_and_attendance":{
                         "label":"Time & Attendance",
                         "link":"/attendance",
                         "class":"link-attendance"
                      },
                      "requests":{
                         "label":"Requests",
                         "link":"/requests",
                         "class":"link-requests"
                      },
                      "talent_directory":{
                         "label":"Talent Directory",
                         "link":"/talents",
                         "class":"link-talentdirectory"
                      },
                      "news_feed":{
                         "label":"News Feed",
                         "link":"/news-feed",
                         "class":"link-newsfeed"
                      },
                      "team_leave_balance":{
                         "label":"Team Leave Balance",
                         "link":"/leave-balance",
                         "class":"link-teamleavebalance"
                      },
                      "dtr_leave_extract":{
                         "label":"Time Record Extractor",
                         "link":"/time-record-extractor",
                         "class":"link-clientextract",
                         "platform":"PAGE"
                      },
                      "view_employee_shift":{
                         "label":"View Employee Shift",
                         "link":"/view-employee-shift",
                         "class":"link-viewshift",
                         "platform":"PAGE"
                      }
                   },
                   "support_team_list":true
                },
                "top_menu":{
                   "faqs":true,
                   "logo":true,
                   "collapsible":true,
                   "impersonate":true,
                   "announcements":true,
                   "notifications":true,
                   "time_recorder":true,
                   "profile":[
                      "ACCOUNT_PROFILE",
                      "LOGOUT",
                      "THEMES",
                      "OPEN_TICKET"
                   ]
                },
                "express_actions":{
                   "main":{
                      "dtr_leave_extract":{
                         "label":"Time Record Extractor",
                         "link":"/time-record-extractor",
                         "class":"link-clientextract",
                         "platform":"PAGE",
                         "is_default":true
                      },
                      "EMERGENCY_NUMBERS":{
                         "label":"Emergency Numbers",
                         "link":"",
                         "class":"item-emergencynumbers",
                         "platform":"MODAL"
                      },
                      "ANNOUNCEMENT":{
                         "label":"Make an Announcement",
                         "link":"/create-announcement",
                         "class":"item-makeannouncement",
                         "platform":"PAGE"
                      }
                   },
                   "role_based":{
                      "PREAPPROVE_OVERTIME":{
                         "label":"Pre-Approved Overtime",
                         "link":"/file-pre-approve-otr",
                         "class":"item-preapproveovertime",
                         "platform":"PAGE",
                         "is_default":true
                      },
                      "PROCESS_REQUEST":{
                         "label":"Process Request",
                         "link":"/requests",
                         "class":"item-processrequest",
                         "platform":"PAGE",
                         "is_default":true
                      },
                      "PREAPPROVE_CHANGE_SHIFT":{
                         "label":"File Shift Schedule",
                         "link":"/view-employee-shift",
                         "class":"item-preapprovechangeshift",
                         "platform":"PAGE"
                      }
                   }
                }
             },
             "composition_code":"COMP-19-000000000002",
             "composition_code_extra":"COMP-19-000000000002"
          },
          "HR":{
             "menus":{
                "top_menu":{
                   "faqs":true,
                   "logo":true,
                   "collapsible":true,
                   "impersonate":true,
                   "notifications":true,
                   "time_recorder":true,
                   "profile":[
                      "ACCOUNT_PROFILE",
                      "LOGOUT",
                      "THEMES",
                      "OPEN_TICKET"
                   ]
                },
                "express_actions":{
                   "main":{
                      "EMERGENCY_NUMBERS":{
                         "label":"Emergency Numbers",
                         "link":"",
                         "class":"item-emergencynumbers",
                         "platform":"MODAL"
                      }
                   },
                   "role_based":{
                      "PREAPPROVE_OVERTIME":{
                         "label":"Pre-Approved Overtime",
                         "link":"/file-pre-approve-otr",
                         "class":"item-preapproveovertime",
                         "platform":"PAGE",
                         "is_default":true
                      },
                      "PREAPPROVE_TOIL":{
                         "label":"Pre-Approved TOIL",
                         "link":"/file-pre-approve-toil",
                         "class":"item-preapprovetoil",
                         "platform":"PAGE",
                         "is_default":true
                      },
                      "team_leave_balance":{
                         "label":"Team Leave Balance",
                         "link":"/leave-balance",
                         "class":"link-teamleavebalance"
                      },
                      "admin_employee_data_extract":{
                         "label":"Employee Info Report",
                         "link":"/personal-data-extract",
                         "class":"link-employeeinforeport"
                      },
                      "dtr_monitoring_data_extract":{
                         "label":"DTR Report Extraction",
                         "link":"/dtr-data-monitoring-extract",
                         "class":"link-dtrreportextraction"
                      },
                      "PROCESS_REQUEST":{
                         "label":"Process Request",
                         "link":"/requests",
                         "class":"item-processrequest",
                         "platform":"PAGE",
                         "is_default":true
                      },
                      "PREAPPROVE_CHANGE_SHIFT":{
                         "label":"File Shift Schedule",
                         "link":"/file-csr",
                         "class":"item-preapprovechangeshift",
                         "platform":"PAGE"
                      }
                   }
                },
                "sidebar":{
                   "pages":{
                      "home":{
                         "label":"Home",
                         "link":"/",
                         "class":"link-home",
                         "platform":"PAGE"
                      },
                      "time_and_attendance":{
                         "label":"Time & Attendance",
                         "link":"/attendance",
                         "class":"link-attendance"
                      },
                      "talent_directory":{
                         "label":"Talent Directory",
                         "link":"/talents-conso",
                         "class":"link-talentdirectory"
                      },
                      "department_directory":{
                         "label":"Department Directory",
                         "link":"/departments",
                         "class":"link-clientdirectory"
                      },
                      "client_directory":{
                         "label":"Client Directory",
                         "link":"/clients-conso",
                         "class":"link-clientsconso"
                      },
                      "requests":{
                         "label":"Requests",
                         "link":"/requests",
                         "class":"link-requests"
                      },
                      "news_feed":{
                         "label":"News Feed",
                         "link":"/news-feed",
                         "class":"link-newsfeed"
                      },
                      "team_leave_balance":{
                         "label":"Team Leave Balance",
                         "link":"/leave-balance",
                         "class":"link-teamleavebalance"
                      },
                      "admin_employee_data_extract":{
                         "label":"Employee Info Report",
                         "link":"/personal-data-extract",
                         "class":"link-employeeinforeport"
                      },
                      "dtr_monitoring_data_extract":{
                         "label":"DTR Report Extraction",
                         "link":"/dtr-data-monitoring-extract",
                         "class":"link-dtrreportextraction"
                      },
                      "view_employee_shift":{
                         "label":"View Employee Shift",
                         "link":"/view-employee-shift",
                         "class":"link-viewshift",
                         "platform":"PAGE"
                      }
                   },
                   "support_team_list":true
                }
             },
             "composition_code":"COMP-20-000000000012",
             "composition_code_extra":"COMP-20-000000000012"
          },
          "RECRUITER":{
             "menus":{
                "sidebar":{
                   "pages":{
                      "home":{
                         "label":"Home",
                         "link":"/",
                         "class":"link-home",
                         "platform":"PAGE"
                      },
                      "news_feed":{
                         "label":"News Feed",
                         "link":"/news-feed",
                         "class":"link-newsfeed"
                      },
                      "fsp":{
                         "label":"Final Staffing Proposal",
                         "link":"/final-staffing-proposal",
                         "class":"link-finalstaffingproposal"
                      },
                      "nha_extractor":{
                         "label":"NHA Extractor",
                         "link":"/nha-extractor",
                         "class":"link-nhaextractor"
                      }
                   },
                   "support_team_list":true
                },
                "top_menu":{
                   "logo":true,
                   "faqs":true,
                   "announcements":true,
                   "notifications":true,
                   "collapsible":true,
                   "impersonate":true,
                   "time_recorder":true,
                   "special_privilege":{
                      "is_allow_download":true,
                      "is_allow_etap":true
                   },
                   "profile":[
                      "ACCOUNT_PROFILE",
                      "LOGOUT",
                      "THEMES",
                      "OPEN_TICKET"
                   ]
                },
                "express_actions":{
                   "main":[
                      
                   ],
                   "role_based":{
                      "fsp_exa":{
                         "label":"Final Staffing Proposal",
                         "link":"/final-staffing-proposal",
                         "class":"link-finalstaffingproposal"
                      },
                      "nha_extractor_exa":{
                         "label":"NHA Extractor",
                         "link":"/nha-extractor",
                         "class":"link-nhaextractor"
                      }
                   }
                }
             },
             "composition_code":"COMP-20-000000000017",
             "composition_code_extra":"COMP-20-000000000017"
          },
          "ADMIN":{
             "menus":{
                "top_menu":{
                   "faqs":true,
                   "logo":true,
                   "collapsible":true,
                   "impersonate":true,
                   "notifications":false,
                   "time_recorder":false,
                   "announcements":false,
                   "profile":[
                      "ACCOUNT_PROFILE",
                      "LOGOUT",
                      "THEMES",
                      "OPEN_TICKET"
                   ]
                },
                "sidebar":{
                   "support_team_list":false,
                   "pages":{
                      "admin_job_lists":{
                         "label":"Job Title",
                         "link":"/admin-job-lists",
                         "class":"link-jobtitle"
                      },
                      "admin_site_list":{
                         "label":"Site",
                         "link":"/admin-site-list",
                         "class":"link-site"
                      },
                      "admin_division_list":{
                         "label":"Division",
                         "link":"/admin-division-list",
                         "class":"link-division"
                      },
                      "admin_department_list":{
                         "label":"Department",
                         "link":"/admin-department-list",
                         "class":"link-department"
                      },
                      "admin_team_list":{
                         "label":"Team",
                         "link":"/admin-team-list",
                         "class":"link-team"
                      },
                      "admin_holiday_management":{
                         "label":"Holiday Management",
                         "link":"",
                         "class":"link-holidaymanagement",
                         "is_child_collapse":false,
                         "children":{
                            "admin_holiday_list":{
                               "label":"Holiday List",
                               "link":"/admin-holiday-list",
                               "class":""
                            },
                            "admin_assign_holiday":{
                               "label":"Assign Holidays",
                               "link":"/admin-assign-holidays",
                               "class":""
                            }
                         }
                      },
                      "admin_audit_trails":{
                         "label":"Audit Trails",
                         "link":"/admin-audit-trails",
                         "class":"link-audittrails"
                      }
                   }
                }
             },
             "composition_code":"COMP-20-000000000016",
             "composition_code_extra":"COMP-20-000000000016"
          },
          "PAYROLL":{
             "menus":{
                "top_menu":{
                   "collapsible":true,
                   "impersonate":true,
                   "announcements":true,
                   "notifications":true,
                   "time_recorder":true,
                   "profile":[
                      "ACCOUNT_PROFILE",
                      "LOGOUT",
                      "THEMES",
                      "OPEN_TICKET"
                   ],
                   "faqs":true,
                   "logo":true
                },
                "express_actions":{
                   "main":{
                      "time_and_attendance":{
                         "label":"Time & Attendance",
                         "link":"/attendance",
                         "class":"link-attendance",
                         "is_default":true
                      },
                      "requests":{
                         "label":"Requests",
                         "link":"/requests",
                         "class":"link-requests",
                         "is_default":true
                      },
                      "team_leave_balance":{
                         "label":"Team Leave Balance",
                         "link":"/leave-balance",
                         "class":"link-teamleavebalance"
                      },
                      "payroll_extract":{
                         "label":"Payroll Extract",
                         "link":"/admin-payroll-extract",
                         "class":"link-payrollextract"
                      },
                      "employee_data_extract":{
                         "label":"Employee Info Report",
                         "link":"/personal-data-extract",
                         "class":"link-employeeinforeport"
                      }
                   },
                   "role_based":{
                      "payroll_services":{
                         "label":"Payroll Services",
                         "link":"/channel/ALL/1",
                         "class":"item-payroll",
                         "platform":"PAGE",
                         "is_default":true
                      }
                   }
                },
                "sidebar":{
                   "pages":{
                      "home":{
                         "label":"Home",
                         "link":"/",
                         "class":"link-home",
                         "platform":"PAGE"
                      },
                      "time_and_attendance":{
                         "label":"Time & Attendance",
                         "link":"/attendance",
                         "class":"link-attendance"
                      },
                      "requests":{
                         "label":"Requests",
                         "link":"/requests",
                         "class":"link-requests"
                      },
                      "talent_directory":{
                         "label":"Talent Directory",
                         "link":"/talents",
                         "class":"link-talentdirectory"
                      },
                      "news_feed":{
                         "label":"News Feed",
                         "link":"/news-feed",
                         "class":"link-newsfeed"
                      },
                      "team_leave_balance":{
                         "label":"Team Leave Balance",
                         "link":"/leave-balance",
                         "class":"link-teamleavebalance"
                      },
                      "payroll_query":{
                         "label":"Payroll Query",
                         "link":"/payroll-query-list",
                         "class":"link-payrollquery"
                      },
                      "payroll_extract":{
                         "label":"Payroll Extract",
                         "link":"/admin-payroll-extract",
                         "class":"link-payrollextract"
                      },
                      "leave_manangement":{
                         "label":"Leave Management",
                         "link":"/admin-add-leave-credit",
                         "class":"link-leavemanagement",
                         "is_child_collapse":false,
                         "children":{
                            "add_leave_credit":{
                               "label":"Add Leave Credit",
                               "link":"/admin-add-leave-credit",
                               "class":"link-newsfeed"
                            }
                         }
                      },
                      "channels":{
                         "label":"Channels",
                         "link":"",
                         "class":"link-channels",
                         "is_child_collapse":false,
                         "children":{
                            "payroll_services":{
                               "label":"Payroll Services",
                               "link":"/channel/ALL/1",
                               "class":"item-payroll",
                               "platform":"PAGE"
                            }
                         }
                      },
                      "view_employee_shift":{
                         "label":"View Employee Shift",
                         "link":"/view-employee-shift",
                         "class":"link-viewshift",
                         "platform":"PAGE"
                      },
                      "employee_data_extract":{
                         "label":"Employee Info Report",
                         "link":"/personal-data-extract",
                         "class":"link-employeeinforeport"
                      }
                   },
                   "support_team_list":true
                }
             },
             "composition_code":"COMP-20-000000000009",
             "composition_code_extra":"COMP-20-000000000009"
          }
       }
    },
    "timeRecord":{
       "load":false,
       "response":{
          "success":true,
          "content":{
             "is_on_leave":false,
             "is_on_rest_day":false,
             "current_date_time":"2021-07-14 14:13:28",
             "employee_profile":{
                "employee_personal_info_first_name":"Mark Augustine",
                "employee_personal_info_last_name":"Jabay",
                "job_title_name":"Mid Quality Assurance Associate"
             },
             "is_has_change_shift":false,
             "shift_data":null,
             "statistics_message":[
                {
                   "insideShiftNoClockIn":"You haven't clocked in yet. The System already tagged you as absent. However, we will still allow you to clock in."
                }
             ],
             "is_can_start_day":true,
             "dtr_analysis":{
                "current_dtr":{
                   "expected_time_in":"07:00:00",
                   "expected_time_out":"16:00:00",
                   "is_holiday":false,
                   "is_required_to_work_on_holiday":false,
                   "grace_period":"10",
                   "flexi_hours":"0",
                   "clock_in_datetime":null,
                   "work_date":null,
                   "clock_out_datetime":null,
                   "clock_in_status":null,
                   "clock_in_status_desc":"",
                   "clock_out_status":null,
                   "clock_out_status_desc":"",
                   "is_rest_day":false,
                   "is_full_flexi":false,
                   "is_critical_day":false,
                   "is_certify":null,
                   "is_on_leave":null,
                   "dtr_id":null,
                   "clock_in_minutes_late":null,
                   "clock_out_excess_hours":null,
                   "clock_out_undertime":null,
                   "clock_in_absent_tag":null,
                   "clock_out_absent_tag":null,
                   "preApprovedOt":null,
                   "preshift_excess_mins":null,
                   "postshift_excess_mins":null,
                   "schedule_type":"STANDARD",
                   "is_follow_dst":false
                }
             }
          },
          "error":""
       },
       "dashboard":true,
       "fetchDTR":false
    },
    "customization":{
       "data":{
          "ABOUTUS":{
             "content_code":"AbOuTajk1JXCmu1m",
             "content_title":"About Us",
             "content_value":"<div> <label htmlFor=\"\">VISION</label> <p>Empower Filipinos to achieve life’s fullest potential without the need to work abroad.</p> </div> <div> <label htmlFor=\"\">MISSION</label> <p>We are transforming the Philippine workplace and with sustainable global careers in amazing, close to home, working environments by delivering best-in-class technology and customized talent-driven solutions for international businesses.</p> </div> <div> <label htmlFor=\"\">VALUES</label> <ul> <li>Talent-driven</li> <li>Client-Centric</li> <li>Transparency</li> <li>Flexibility</li> <li>Partnerships</li> </ul> </div>",
             "content_type":"ABOUTUS",
             "content_format":"HTML",
             "content_company_code":null,
             "content_is_priority":false,
             "content_tab_image":"https://assets.empowerteams.io/images/img-aboutcompany.jpg",
             "content_video_url":null
          },
          "OURSERVICES":{
             "content_code":"s3rv1c3su4b123ka",
             "content_title":"The EMAPTA Difference",
             "content_value":"<h5>Staff First</h5> <p>At the core of everything we do is our staff's welfare and best interest. We understand that our entire business model relies on our ability to attract, develop, and retain high-quality talent.</p> <h5>Australian Leadership Engagement</h5> <p>Emapta's leadership team is fully hands-on to ensure the fulfillment of the client's business goals. Our entire management team, support staff, and the CEO are always accessible to all our employees and clients.</p> <h5>Network of Offices &amp; Remote Workplace Solutions</h5> <p>Our fourteen world-class offices are strategically located in commuter-friendly business hubs to provide an optimum working environment.</p> <p>Equally, <em>Emapta Anywhere™</em> let staff work remotely from home or in any location protected by our enterprise-grade data security system.</p> <h5>Training &amp; Development</h5> <p>At Emapta, we invest in our employee's future through personal and professional development programs to empower them in becoming invaluable members of their teams.</p> <h5>Engagement &amp; Retention</h5> <p>Emapta promotes work/life balance to help employees maintain a healthy well-being through continuous talent engagement activities, recognition, and health and wellness programs.</p></div>",
             "content_type":"OURSERVICES",
             "content_format":"HTML",
             "content_company_code":null,
             "content_is_priority":true,
             "content_tab_image":"https://assets.empowerteams.io/images/img-emapta-services.jpg",
             "content_video_url":null
          },
          "DASHBOARD":{
             "content_code":"J1pZcykynD9zADjs",
             "content_title":"Dashboard",
             "content_value":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget fermentum ipsum, vitae finibus orci. Vestibulum ac tincidunt nisi. Aliquam laoreet efficitur congue. Quisque facilisis elit arcu, ut interdum ligula aliquam vel. Sed convallis rutrum condimentum. Aenean vel odio in nunc scelerisque bibendum nec sit amet libero. Phasellus vel ante viverra, feugiat mi eu, faucibus erat. Nulla molestie ex vel enim hendrerit, eu pretium risus bibendum.",
             "content_type":"DASHBOARD",
             "content_format":"HTML",
             "content_company_code":null,
             "content_is_priority":true,
             "content_tab_image":" https://assets.empowerteams.io/images/empower-v2/emapta/emapta-banner.jpg",
             "content_video_url":null
          },
          "CEOMESSAGE":{
             "content_code":"J1pZcykynD9zADtl",
             "content_title":"CEO Message",
             "content_value":"https://player.vimeo.com/video/451065548",
             "content_type":"CEOMESSAGE",
             "content_format":"VIDEO",
             "content_company_code":null,
             "content_is_priority":true,
             "content_tab_image":"https://assets.empowerteams.io/images/empower-v2/emapta/emapta-ceo.jpg",
             "content_video_url":"https://archive.org/embed/5-mar-2021-video-1-1-1"
          },
          "PORTRAITDASHBOARD":{
             "content_code":"J1pZcykynD9zsADajs",
             "content_title":"Clock",
             "content_value":"<p>Always check your records/transactions, and update them if necessary.</p>",
             "content_type":"PORTRAITDASHBOARD",
             "content_format":"HTML",
             "content_company_code":null,
             "content_is_priority":true,
             "content_tab_image":"https://assets.empowerteams.io/images/essentials/emapta/emapta-welcome.svg",
             "content_video_url":null
          },
          "ABOUTUSNEW":{
             "content_code":"J1pZcykynD9zADajs",
             "content_title":"Portrait Dashboard",
             "content_value":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget fermentum ipsum, vitae finibus orci. Vestibulum ac tincidunt nisi. Aliquam laoreet efficitur congue. Quisque facilisis elit arcu, ut interdum ligula aliquam vel. Sed convallis rutrum condimentum. Aenean vel odio in nunc scelerisque bibendum nec sit amet libero. Phasellus vel ante viverra, feugiat mi eu, faucibus erat. Nulla molestie ex vel enim hendrerit, eu pretium risus bibendum.",
             "content_type":"ABOUTUSNEW",
             "content_format":"HTML",
             "content_company_code":null,
             "content_is_priority":true,
             "content_tab_image":" https://assets.empowerteams.io/images/empower-v2/emapta/emapta-about.jpg",
             "content_video_url":null
          },
          "VISION":{
             "content_code":"09BAsklj1akjajj",
             "content_title":null,
             "content_value":"<div>\n<label htmlFor=\"\">VISION</label>\n<p>Empower Filipinos to achieve life’s fullest potential without the need to work abroad.</p>\n</div>\n\n<div>\n<label htmlFor=\"\">MISSION</label>\n<p>We are transforming the Philippine workplace and with sustainable global careers in amazing, close to home, working environments by delivering best-in-class technology and customized talent-driven solutions for international businesses.</p>\n</div>\n\n<div>\n<label htmlFor=\"\">FASTER COMPANY VALUES</label>\n<ul>\n<li><p><b>F</b>lexible - We do what it takes and adapt quickly to overcome any challenge or meet any opportunity. We add what is necessary and remove what is not, embrace what is new and flex when change is the answer to the question.</p></li> \n<li><p><b>A</b>spirational - We lead by example, innovate, and always look for a smarter way. We always think bigger, and how to be better. Aspiration got us to where we are and drives us to where we are going.</p></li>\n<li><p><b>S</b>ynchronized - Like the movement of a clock, we are a group of individuals working together as a team with a common goal top of mind. We are in sync with our customers, our partners, and our people, driving forward as one.</p></li>\n<li><p><b>T</b>ransparent - We take and open and direct approach with our people, our partners, and our customers. We remove the fluff and stick to facts, share what is working and what is not. If we make a mistake, we own it, fix it, and quickly move forward. We set expectations and deliver on our promises.</p></li>\n<li><p><b>E</b>mpowered - We enable our customers and partners to grow stronger and go further. We find great people, empower them, and set them free. We support them every step of the way with the right skilled resources, tools, development, and environment, to achieve great things.</p></li>\n<li><p><b>R</b>elationships - Relationships are in our DNA. They are the glue that bond us and allow us to grow stronger and faster together with our customers, our partners, and our team members.</p></li>\n</ul>\n</div>",
             "content_type":"VISION",
             "content_format":"HTML",
             "content_company_code":null,
             "content_is_priority":false,
             "content_tab_image":null,
             "content_video_url":null
          }
       }
    },
    "announcement":{
       "modal":true
    },
    "_persist":{
       "version":-1,
       "rehydrated":true
    }
  }